MAKE      = mingw32-make.exe

all:
	$(MAKE) -C guihead -f Makefile.win all
	$(MAKE) -C consolehead -f Makefile.win all
	$(MAKE) -C jniguihead_BETA -f Makefile.win all
	$(MAKE) -C jniconsolehead_BETA -f Makefile.win all

clean:
	$(MAKE) -C guihead -f Makefile.win clean
	$(MAKE) -C consolehead -f Makefile.win clean
	$(MAKE) -C jniguihead_BETA -f Makefile.win clean
	$(MAKE) -C jniconsolehead_BETA -f Makefile.win clean
