#!/bin/sh

if [ -z "$FIGTREE" ]; then
	## resolve links - $0 may be a link to application
	PRG="$0"

	# need this for relative symlinks
	while [ -h "$PRG" ] ; do
	    ls=`ls -ld "$PRG"`
	    link=`expr "$ls" : '.*-> \(.*\)$'`
	    if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	    else
		PRG="`dirname "$PRG"`/$link"
	    fi
	done

	# make it fully qualified
	saveddir=`pwd`
	FIGTREE0=`dirname "$PRG"`/..
	FIGTREE=`cd "$FIGTREE0" && pwd`
	cd "$saveddir"
fi

FIGTREE_LIB="$FIGTREE/lib"

java -Xms64m -Xmx512m -jar $FIGTREE_LIB/figtree.jar "$@"
